# Generated by Django 4.2.7 on 2025-03-16 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alfa', 'Alfa')], max_length=10)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('bulan', models.CharField(max_length=10)),
                ('tahun', models.IntegerField()),
                ('jam_absensi', models.TimeField(auto_now_add=True)),
                ('lokasi', models.CharField(max_length=255)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
