# Generated by Django 4.2.7 on 2025-03-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birruwattaqwa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='bulan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='lokasi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
