# Generated by Django 4.2.7 on 2025-04-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birruwattaqwa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalguru',
            name='jam_mulai',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='jadwalguru',
            name='jam_selesai',
            field=models.TimeField(),
        ),
    ]
