# Generated by Django 4.2.7 on 2025-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birruwattaqwa', '0002_alter_jadwalguru_jam_mulai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LokasiAbsen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tempat', models.CharField(default='Sekolah', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_meter', models.IntegerField(default=50)),
            ],
        ),
    ]
