# Generated by Django 4.2.7 on 2025-03-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birruwattaqwa', '0003_rename_keterangan_absensi_alasan_izin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
