# Generated by Django 4.2.7 on 2025-06-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birruwattaqwa', '0004_kelas_matapelajaran_alter_jadwalguru_kelas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JadwalGuru',
        ),
        migrations.DeleteModel(
            name='MataPelajaran',
        ),
    ]
