# Generated by Django 4.2.7 on 2025-03-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birruwattaqwa', '0004_absensi_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='bulan',
            field=models.CharField(max_length=20),
        ),
    ]
