# Generated by Django 4.2.7 on 2025-06-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birruwattaqwa', '0005_delete_jadwalguru_delete_matapelajaran'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kelas',
        ),
    ]
