# Generated by Django 4.2.7 on 2025-03-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birruwattaqwa', '0005_alter_absensi_bulan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensi',
            name='alasan_izin',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='alasan_sakit',
        ),
    ]
