# Generated by Django 4.2.7 on 2025-03-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birruwattaqwa', '0006_remove_absensi_alasan_izin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
