# Generated by Django 4.2.7 on 2025-03-19 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birruwattaqwa', '0007_absensi_latitude_absensi_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=20)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('mata_pelajaran', models.CharField(max_length=100)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
