# Generated by Django 4.2.7 on 2025-03-19 17:35

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('birruwattaqwa', '0009_profilguru'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='absensi',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
