# Generated by Django 4.2.7 on 2025-04-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birruwattaqwa', '0012_dailyqrcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
